/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1edd;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Andrea
 */
public class Cargar extends javax.swing.JFrame {

    /**
     * Creates new form Cargar
     */
    public Cargar() {
        initComponents();
        
        JScrollPane es = new JScrollPane();
        es.setBounds(20,20,700,450);
        es.setViewportView(this.jPanel1);
        es.getViewport().setView(this.jPanel1);
        getContentPane().add(es);
        this.setBounds(50, 50, 1200, 600);
        setLocationRelativeTo(null);
       
  
    }
    
     int contador=1;
     boolean a = true;
     boolean c = true;
     static ListaDoble listaD = new ListaDoble();
     NodoDoble ayuda;
     
     
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jmario = new javax.swing.JButton();
        Jficha = new javax.swing.JButton();
        Jhongo = new javax.swing.JButton();
        Jcastillo = new javax.swing.JButton();
        Jsuelo = new javax.swing.JButton();
        Jpared = new javax.swing.JButton();
        Jkoopa = new javax.swing.JButton();
        Jgoomba1 = new javax.swing.JButton();
        jtho = new javax.swing.JTextField();
        jtgoo = new javax.swing.JTextField();
        jtmario = new javax.swing.JTextField();
        jttor = new javax.swing.JTextField();
        jtsu = new javax.swing.JTextField();
        jtpa = new javax.swing.JTextField();
        jtca = new javax.swing.JTextField();
        jtmo = new javax.swing.JTextField();
        Jcargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 22, 891, 440);

        Jmario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mariopp.jpg"))); // NOI18N
        Jmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmarioActionPerformed(evt);
            }
        });

        Jficha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/monedap.png"))); // NOI18N
        Jficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JfichaActionPerformed(evt);
            }
        });

        Jhongo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hongop.jpg"))); // NOI18N
        Jhongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhongoActionPerformed(evt);
            }
        });

        Jcastillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/castillop.jpg"))); // NOI18N
        Jcastillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcastilloActionPerformed(evt);
            }
        });

        Jsuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/suelop.jpg"))); // NOI18N
        Jsuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsueloActionPerformed(evt);
            }
        });

        Jpared.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paredp.jpg"))); // NOI18N
        Jpared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JparedActionPerformed(evt);
            }
        });

        Jkoopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tortugap.jpg"))); // NOI18N
        Jkoopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkoopaActionPerformed(evt);
            }
        });

        Jgoomba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goombap.jpg"))); // NOI18N
        Jgoomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jgoomba1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jmario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Jkoopa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtmario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jttor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jgoomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Jficha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtgoo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jtmo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jhongo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Jpared, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jtpa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jsuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Jcastillo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtsu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jtca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jmario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jkoopa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jttor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jgoomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jficha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtgoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jhongo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jpared, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jsuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Jcastillo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(925, 22, 244, 509);

        Jcargar.setText("CARGAR");
        Jcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcargarActionPerformed(evt);
            }
        });
        getContentPane().add(Jcargar);
        Jcargar.setBounds(765, 489, 108, 53);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void JcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcargarActionPerformed
        // TODO add your handling code here:
      JuegoM ju = new JuegoM();
      ju.setVisible(true); 
      this.dispose();
    }//GEN-LAST:event_JcargarActionPerformed

    private void JmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmarioActionPerformed
    if(a== true){ 
        
        listaD.AgregaralInicio(new Elemento(10,30,this.jtmario.getText(),"MARIO"));
    this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\mariopp.jpg",
    "MARIO", this.jtmario);
     
    
   }else{
       JOptionPane.showMessageDialog(null, "Su personaje principal ya fue agregado","ERROR",JOptionPane.ERROR_MESSAGE);
   } 
   a=false;
    }//GEN-LAST:event_JmarioActionPerformed

    private void JkoopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkoopaActionPerformed
        // TODO add your handling code here:
        listaD.AgregaralInicio(new Elemento(10,30,this.jttor.getText(),"TORTUGA"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\tortugap.jpg",
            "TORTUGA", this.jttor);
   
    }//GEN-LAST:event_JkoopaActionPerformed

    private void Jgoomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jgoomba1ActionPerformed
        // TODO add your handling code here:
         listaD.AgregaralInicio(new Elemento(10,30,this.jtgoo.getText(),"GOOMBA"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\goombap.jpg",
            "GOOMBA", this.jtgoo);
   
    }//GEN-LAST:event_Jgoomba1ActionPerformed

    private void JfichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JfichaActionPerformed
        // TODO add your handling code here:
         listaD.AgregaralInicio(new Elemento(10,30,this.jtmo.getText(),"MONEDA"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\monedap.png",
            "MONEDA", this.jtmo);
   
    }//GEN-LAST:event_JfichaActionPerformed

    private void JhongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhongoActionPerformed
        // TODO add your handling code here:
         listaD.AgregaralInicio(new Elemento(10,30,this.jtho.getText(),"HONGO"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\hongop.jpg",
            "HONGO", this.jtho);
   
    }//GEN-LAST:event_JhongoActionPerformed

    private void JparedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JparedActionPerformed
        // TODO add your handling code here:
        listaD.AgregaralInicio(new Elemento(10,30,this.jtpa.getText(),"PARED")); 
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\paredp.jpg",
            "PARED", this.jtpa);
   
    }//GEN-LAST:event_JparedActionPerformed

    private void JsueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsueloActionPerformed
        // TODO add your handling code here:
       listaD.AgregaralInicio(new Elemento(10,30,this.jtsu.getText(),"SUELO"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\suelop.jpg",
            "SUELO", this.jtsu);
   
    }//GEN-LAST:event_JsueloActionPerformed

    private void JcastilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcastilloActionPerformed
        // TODO add your handling code here:
      if(c == true){ 
          listaD.AgregaralInicio(new Elemento(10,30,this.jtca.getText(),"CASTILLO"));
        this.agregar("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\Practica1s22015EDD_201020250\\Practica1EDD\\src\\imagenes\\castillop.jpg",
            "CASTILLO", this.jtca);
   
   }else{
       JOptionPane.showMessageDialog(null, "El castillo ya fue agregado","ERROR",JOptionPane.ERROR_MESSAGE);
   } 
         c=false;
    }//GEN-LAST:event_JcastilloActionPerformed

    public void agregar(String ruta, String tipoObj, JTextField cuadro)
{
    
    ImageIcon ii = new ImageIcon(ruta);
    JLabel imagen = new JLabel();
    imagen.setIcon(ii);
    imagen.setBounds(10, 50 + (contador * 70), 60, 60);
    this.jPanel1.add(imagen);

    
    JLabel tipo = new JLabel();
    tipo.setText(tipoObj);
    tipo.setBounds(10, 50 + (contador * 70), 60, 32);
    this.jPanel1.add(tipo);
    
    JLabel nombre = new JLabel();
    nombre.setText(cuadro.getText());
    nombre.setBounds(100, 50 + (contador * 70), 150, 32);
    this.jPanel1.add(nombre);
    
    JButton cambiar = new JButton();  
    cambiar.setText("Renombrar");
    cambiar.setBounds(325, 50 + (contador * 70), 100, 32);
    this.jPanel1.add(cambiar);
    cambiar.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            String cam =JOptionPane.showInputDialog(null,"Ingrese Nuevo Nombre","");
               nombre.setText(cam);
               ayuda.es.nombre=cam;
              }
          });
       this.jPanel1.add(cambiar);
    
    
  
    
    JButton eliminar = new JButton();  
    eliminar.setText("Eliminar");
    eliminar.setBounds(475, 50 + (contador * 70), 100, 32);
    this.jPanel1.add(eliminar);
    eliminar.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {   
                 
            }
        });
        
       
      this.jPanel1.repaint();

    jPanel1.setPreferredSize(new Dimension(650,300 + (contador * 50)));
    contador++; 
}
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jcargar;
    private javax.swing.JButton Jcastillo;
    private javax.swing.JButton Jficha;
    private javax.swing.JButton Jgoomba1;
    private javax.swing.JButton Jhongo;
    private javax.swing.JButton Jkoopa;
    private javax.swing.JButton Jmario;
    private javax.swing.JButton Jpared;
    private javax.swing.JButton Jsuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtca;
    private javax.swing.JTextField jtgoo;
    private javax.swing.JTextField jtho;
    private javax.swing.JTextField jtmario;
    private javax.swing.JTextField jtmo;
    private javax.swing.JTextField jtpa;
    private javax.swing.JTextField jtsu;
    private javax.swing.JTextField jttor;
    // End of variables declaration//GEN-END:variables
}
